#!/bin/bash
# ITSM Admin System - Quick Start Script

echo "═══════════════════════════════════════════════════════════════"
echo "  ITSM Admin System - Quick Start"
echo "═══════════════════════════════════════════════════════════════"
echo ""

echo "Step 1️⃣  - Create Database"
echo "─────────────────────────────────────────────────────────────"
echo "Run in MySQL:"
echo "  CREATE DATABASE IF NOT EXISTS itsm_db;"
echo ""
echo "Or execute:"
echo "  mysql -u root -p2005 -e 'CREATE DATABASE itsm_db;'"
echo ""

echo "Step 2️⃣  - Build Application"
echo "─────────────────────────────────────────────────────────────"
echo "mvn clean install"
echo ""

echo "Step 3️⃣  - Run Application"
echo "─────────────────────────────────────────────────────────────"
echo "mvn spring-boot:run"
echo ""

echo "Step 4️⃣  - Test Login"
echo "─────────────────────────────────────────────────────────────"
echo "curl -X POST http://localhost:8080/api/auth/login \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"email\":\"admin@college.edu\",\"password\":\"admin123\"}'"
echo ""

echo "Step 5️⃣  - Save Token & Test API"
echo "─────────────────────────────────────────────────────────────"
echo "TOKEN=<your_token_from_login>"
echo ""
echo "Then test endpoints:"
echo ""
echo "# Get all users"
echo "curl -H 'Authorization: Bearer \$TOKEN' http://localhost:8080/api/admin/users"
echo ""
echo "# Get all tickets"
echo "curl -H 'Authorization: Bearer \$TOKEN' http://localhost:8080/api/admin/tickets"
echo ""
echo "# Get all assets"
echo "curl -H 'Authorization: Bearer \$TOKEN' http://localhost:8080/api/admin/assets"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "  Default Login Credentials"
echo "═══════════════════════════════════════════════════════════════"
echo "Email:    admin@college.edu"
echo "Password: admin123"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "  Documentation Files"
echo "═══════════════════════════════════════════════════════════════"
echo "1. FINAL_DELIVERY_SUMMARY.md     - What was delivered"
echo "2. ADMIN_QUICK_START.md          - Getting started"
echo "3. ADMIN_API_DOCUMENTATION.md    - API reference"
echo "4. ADMIN_VISUAL_GUIDE.md         - Architecture diagrams"
echo "5. IMPLEMENTATION_CHECKLIST.md   - What was implemented"
echo "6. README_ADMIN_SYSTEM.md        - System overview"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "  12 API Endpoints"
echo "═══════════════════════════════════════════════════════════════"
echo "1.  POST   /api/auth/login                    - Login"
echo "2.  GET    /api/admin/users                   - List users"
echo "3.  GET    /api/admin/users/{id}              - Get user"
echo "4.  POST   /api/admin/users                   - Create user"
echo "5.  GET    /api/admin/tickets                 - List tickets"
echo "6.  GET    /api/admin/tickets/{id}            - Get ticket"
echo "7.  GET    /api/admin/tickets/status/{status} - Filter by status"
echo "8.  PUT    /api/admin/tickets/{id}/assign/{eng} - Assign engineer"
echo "9.  PUT    /api/admin/tickets/{id}/status     - Update status"
echo "10. GET    /api/admin/assets                  - List assets"
echo "11. GET    /api/admin/assets/{id}             - Get asset"
echo "12. POST   /api/admin/assets                  - Create asset"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "  Ready to Go! ✨"
echo "═══════════════════════════════════════════════════════════════"
